### ISSUE TITLE
creating users in cryptpad?

### ISSUE THREAD

**Issue by anthonymobile** [tchapi/own-private-cloud#7]
how are you managing users in the Cryptpad container? trying to just build that stack separately and not sure how its setup

**Comment by tchapi** [comment]
Hi @anthonymobile and thanks for your interest

As of today, my need is to have only one user (myself). So I create it via the regular signup method (once the container is up and running).

Then, I get the admin key from this account and feed it to https://github.com/tchapi/own-private-cloud/blob/master/configurations/cryptpad/config.js.template so that my account is an administrator of everything.

As I don't need other accounts, I disabled registration entirely (see https://github.com/xwiki-labs/cryptpad/issues/242 for more details).

I would love to have a more robust approach but so far there are no real options for this. Hope the Cryptpad team can work something out soon !

Best
